//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.OpenData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenDataViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenDataViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.OpenData.Resources.OpenDataViewRes", typeof(OpenDataViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking the buttons below can take a long time to execute. Sometime a few minutes..
        /// </summary>
        public static string ClickingTheButtonsBelowCanTakeALongTimeToExecuteSometimeAFewMinutes {
            get {
                return ResourceManager.GetString("ClickingTheButtonsBelowCanTakeALongTimeToExecuteSometimeAFewMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        public static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSV document of MWQM samples.
        /// </summary>
        public static string GenerateCSVDocumentOfMWQMSamples {
            get {
                return ResourceManager.GetString("GenerateCSVDocumentOfMWQMSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSV document of MWQM sites.
        /// </summary>
        public static string GenerateCSVDocumentOfMWQMSites {
            get {
                return ResourceManager.GetString("GenerateCSVDocumentOfMWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate KMZ document of MWQM sites.
        /// </summary>
        public static string GenerateKMZDocumentOfMWQMSites {
            get {
                return ResourceManager.GetString("GenerateKMZDocumentOfMWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate XLSX document of MWQM samples.
        /// </summary>
        public static string GenerateXlsxDocumentOfMWQMSamples {
            get {
                return ResourceManager.GetString("GenerateXlsxDocumentOfMWQMSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load setup.
        /// </summary>
        public static string LoadSetup {
            get {
                return ResourceManager.GetString("LoadSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all routine sample for MWQM Site as.
        /// </summary>
        public static string MarkAllRoutineSamplesForMWQMSiteAs {
            get {
                return ResourceManager.GetString("MarkAllRoutineSamplesForMWQMSiteAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all routine sample for province as.
        /// </summary>
        public static string MarkAllRoutineSamplesForProvinceAs {
            get {
                return ResourceManager.GetString("MarkAllRoutineSamplesForProvinceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all routine sample for subsector as.
        /// </summary>
        public static string MarkAllRoutineSamplesForSubsectorAs {
            get {
                return ResourceManager.GetString("MarkAllRoutineSamplesForSubsectorAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not use for open data.
        /// </summary>
        public static string NotUseForOpenData {
            get {
                return ResourceManager.GetString("NotUseForOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data document production.
        /// </summary>
        public static string OpenDataDocumentProduction {
            get {
                return ResourceManager.GetString("OpenDataDocumentProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH.
        /// </summary>
        public static string pH {
            get {
                return ResourceManager.GetString("pH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sal.
        /// </summary>
        public static string Sal {
            get {
                return ResourceManager.GetString("Sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitive.
        /// </summary>
        public static string Sensitive {
            get {
                return ResourceManager.GetString("Sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide MWQM samples.
        /// </summary>
        public static string ShowOrHideMWQMSamples {
            get {
                return ResourceManager.GetString("ShowOrHideMWQMSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide MWQM site list.
        /// </summary>
        public static string ShowOrHideMWQMSiteList {
            get {
                return ResourceManager.GetString("ShowOrHideMWQMSiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        public static string Stat {
            get {
                return ResourceManager.GetString("Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for open data.
        /// </summary>
        public static string UseForOpenData {
            get {
                return ResourceManager.GetString("UseForOpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can click the stat button to see the status of the task.
        /// </summary>
        public static string YouCanClickTheStatButtonToSeeTheStatusOfTheTask {
            get {
                return ResourceManager.GetString("YouCanClickTheStatButtonToSeeTheStatusOfTheTask", resourceCulture);
            }
        }
    }
}
