//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.HydrometricSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HydrometricSiteViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HydrometricSiteViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.HydrometricSite.Resources.HydrometricSiteViewRes", typeof(HydrometricSiteViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dash [-] between two years represent: from year to year inclusively.
        /// </summary>
        public static string ADashBetweenTwoYearsRepresentFromYearToYearInclusively {
            get {
                return ResourceManager.GetString("ADashBetweenTwoYearsRepresentFromYearToYearInclusively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any space will be omitted.
        /// </summary>
        public static string AnySpaceWillBeOmitted {
            get {
                return ResourceManager.GetString("AnySpaceWillBeOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything unrecognized - the user will receive an error message.
        /// </summary>
        public static string AnythingUnrecognizedTheUserWillReceiveAnErrorMessage {
            get {
                return ResourceManager.GetString("AnythingUnrecognizedTheUserWillReceiveAnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A year between two commas represent that year.
        /// </summary>
        public static string AYearBetweenTwoCommasRepresentThatYear {
            get {
                return ResourceManager.GetString("AYearBetweenTwoCommasRepresentThatYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on globe icon to view on map.
        /// </summary>
        public static string ClickOnGlobeIconToViewOnMap {
            get {
                return ResourceManager.GetString("ClickOnGlobeIconToViewOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending with a dash [-] represent up to current year.
        /// </summary>
        public static string EndingWithADashRepresentUpToCurrentYear {
            get {
                return ResourceManager.GetString("EndingWithADashRepresentUpToCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find hydrometric sites within distance of subsector.
        /// </summary>
        public static string FindHydrometricSitesWithinDistanceOfSubsector {
            get {
                return ResourceManager.GetString("FindHydrometricSitesWithinDistanceOfSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrometric sites to use for subsector verify and save.
        /// </summary>
        public static string HydrometricSitesToUseForSubsectorVerifyAndSave {
            get {
                return ResourceManager.GetString("HydrometricSitesToUseForSubsectorVerifyAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrometric sites used and within distance.
        /// </summary>
        public static string HydrometricSitesUsedAndWithinDistance {
            get {
                return ResourceManager.GetString("HydrometricSitesUsedAndWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify on map.
        /// </summary>
        public static string IdentifyOnMap {
            get {
                return ResourceManager.GetString("IdentifyOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save button at bottom of page.
        /// </summary>
        public static string SaveButtonAtBottomOfPage {
            get {
                return ResourceManager.GetString("SaveButtonAtBottomOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an adjacent subsector.
        /// </summary>
        public static string SelectAnAdjacentSubsector {
            get {
                return ResourceManager.GetString("SelectAnAdjacentSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hydrometric sites on map.
        /// </summary>
        public static string ShowHydrometricSitesOnMap {
            get {
                return ResourceManager.GetString("ShowHydrometricSitesOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use same hydrometric sites as selected subsector.
        /// </summary>
        public static string UseSameHydrometricSitesAsSelectedSubsector {
            get {
                return ResourceManager.GetString("UseSameHydrometricSitesAsSelectedSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of use.
        /// </summary>
        public static string YearsOfUse {
            get {
                return ResourceManager.GetString("YearsOfUse", resourceCulture);
            }
        }
    }
}
