//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.Map.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.Map.Resources.MapViewRes", typeof(MapViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All activities.
        /// </summary>
        public static string AllActivities {
            get {
                return ResourceManager.GetString("AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All locations.
        /// </summary>
        public static string AllLocations {
            get {
                return ResourceManager.GetString("AllLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        public static string Area_abr {
            get {
                return ResourceManager.GetString("Area_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM.
        /// </summary>
        public static string BoxModel_abr {
            get {
                return ResourceManager.GetString("BoxModel_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to:.
        /// </summary>
        public static string BrowseTo {
            get {
                return ResourceManager.GetString("BrowseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        public static string Contacts_abr {
            get {
                return ResourceManager.GetString("Contacts_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSP - Web Tools.
        /// </summary>
        public static string CSSPApps {
            get {
                return ResourceManager.GetString("CSSPApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSPWebTools.
        /// </summary>
        public static string CSSPWebTools {
            get {
                return ResourceManager.GetString("CSSPWebTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease map size.
        /// </summary>
        public static string DecreaseMapSize {
            get {
                return ResourceManager.GetString("DecreaseMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding or collapsing legend.
        /// </summary>
        public static string ExpandOrCollapseLegend {
            get {
                return ResourceManager.GetString("ExpandOrCollapseLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Map.
        /// </summary>
        public static string HideMap {
            get {
                return ResourceManager.GetString("HideMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Icons.
        /// </summary>
        public static string ImageIcons {
            get {
                return ResourceManager.GetString("ImageIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase map size.
        /// </summary>
        public static string IncreaseMapSize {
            get {
                return ResourceManager.GetString("IncreaseMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        public static string InfInformation_abr {
            get {
                return ResourceManager.GetString("InfInformation_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF.
        /// </summary>
        public static string Infrastructure_abr {
            get {
                return ResourceManager.GetString("Infrastructure_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress ....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons&apos; name.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language option.
        /// </summary>
        public static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE.
        /// </summary>
        public static string Legend_abr {
            get {
                return ResourceManager.GetString("Legend_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to share.
        /// </summary>
        public static string LinkToShare {
            get {
                return ResourceManager.GetString("LinkToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string Lng {
            get {
                return ResourceManager.GetString("Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading .
        /// </summary>
        public static string LoadingApp {
            get {
                return ResourceManager.GetString("LoadingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map helper.
        /// </summary>
        public static string MapHelper {
            get {
                return ResourceManager.GetString("MapHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker size.
        /// </summary>
        public static string MarkerSize {
            get {
                return ResourceManager.GetString("MarkerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page description.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string MikeScenario_abr {
            get {
                return ResourceManager.GetString("MikeScenario_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move label.
        /// </summary>
        public static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU.
        /// </summary>
        public static string Municipality_abr {
            get {
                return ResourceManager.GetString("Municipality_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR.
        /// </summary>
        public static string MWQMRun_abr {
            get {
                return ResourceManager.GetString("MWQMRun_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        public static string MWQMSite_abr {
            get {
                return ResourceManager.GetString("MWQMSite_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active.
        /// </summary>
        public static string OnlyActive {
            get {
                return ResourceManager.GetString("OnlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Icons.
        /// </summary>
        public static string PlainIcons {
            get {
                return ResourceManager.GetString("PlainIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        public static string PollutionSourceSite_abr {
            get {
                return ResourceManager.GetString("PollutionSourceSite_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this page.
        /// </summary>
        public static string ShareThisPage {
            get {
                return ResourceManager.GetString("ShareThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string ShowAreas {
            get {
                return ResourceManager.GetString("ShowAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Model.
        /// </summary>
        public static string ShowBoxModel {
            get {
                return ResourceManager.GetString("ShowBoxModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ShowContacts {
            get {
                return ResourceManager.GetString("ShowContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructures Information.
        /// </summary>
        public static string ShowInfInformation {
            get {
                return ResourceManager.GetString("ShowInfInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructures.
        /// </summary>
        public static string ShowInfrastructure {
            get {
                return ResourceManager.GetString("ShowInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show less text in map markers.
        /// </summary>
        public static string ShowLessTextInMapMarkers {
            get {
                return ResourceManager.GetString("ShowLessTextInMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike Scenarios.
        /// </summary>
        public static string ShowMikeScenario {
            get {
                return ResourceManager.GetString("ShowMikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more text in map markers.
        /// </summary>
        public static string ShowMoreTextInMapMarkers {
            get {
                return ResourceManager.GetString("ShowMoreTextInMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalities.
        /// </summary>
        public static string ShowMunicipalities {
            get {
                return ResourceManager.GetString("ShowMunicipalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWQM Runs.
        /// </summary>
        public static string ShowMWQMRuns {
            get {
                return ResourceManager.GetString("ShowMWQMRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWQM Sites.
        /// </summary>
        public static string ShowMWQMSites {
            get {
                return ResourceManager.GetString("ShowMWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Sources.
        /// </summary>
        public static string ShowPollutionSources {
            get {
                return ResourceManager.GetString("ShowPollutionSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Plumes.
        /// </summary>
        public static string ShowVisualPlumes {
            get {
                return ResourceManager.GetString("ShowVisualPlumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site management.
        /// </summary>
        public static string SiteAdmin {
            get {
                return ResourceManager.GetString("SiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP.
        /// </summary>
        public static string VisualPlumes_abr {
            get {
                return ResourceManager.GetString("VisualPlumes_abr", resourceCulture);
            }
        }
    }
}
