//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.RainExceedance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RainExceedanceViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RainExceedanceViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.RainExceedance.Resources.RainExceedanceViewRes", typeof(RainExceedanceViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new rain exceedance.
        /// </summary>
        public static string AddANewRainExceedance {
            get {
                return ResourceManager.GetString("AddANewRainExceedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After saving the rain exceedance with lat lng, you will be able to select climate sites.
        /// </summary>
        public static string AfterSavingTheRainExceedanceWithLatLngYouWillBeAbleToSelectClimateSites {
            get {
                return ResourceManager.GetString("AfterSavingTheRainExceedanceWithLatLngYouWillBeAbleToSelectClimateSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to provinces.
        /// </summary>
        public static string ApplyToProvince {
            get {
                return ResourceManager.GetString("ApplyToProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to subsectors.
        /// </summary>
        public static string ApplyToSubsector {
            get {
                return ResourceManager.GetString("ApplyToSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate Location.
        /// </summary>
        public static string ApproximateLocation {
            get {
                return ResourceManager.GetString("ApproximateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on globe icon to view on map.
        /// </summary>
        public static string ClickOnGlobeIconToViewOnMap {
            get {
                return ResourceManager.GetString("ClickOnGlobeIconToViewOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the edit button to create or modify rain exceedances.
        /// </summary>
        public static string ClickTheEditButtonToCreateOrModifyRainExceedances {
            get {
                return ResourceManager.GetString("ClickTheEditButtonToCreateOrModifyRainExceedances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add.
        /// </summary>
        public static string ClickToAdd {
            get {
                return ResourceManager.GetString("ClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to remove.
        /// </summary>
        public static string ClickToRemove {
            get {
                return ResourceManager.GetString("ClickToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites not to use.
        /// </summary>
        public static string ClimateSitesNotToUse {
            get {
                return ResourceManager.GetString("ClimateSitesNotToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites to use.
        /// </summary>
        public static string ClimateSitesToUse {
            get {
                return ResourceManager.GetString("ClimateSitesToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites used and within distance.
        /// </summary>
        public static string ClimateSitesUsedAndWithinDistance {
            get {
                return ResourceManager.GetString("ClimateSitesUsedAndWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Rain Exceedance.
        /// </summary>
        public static string CreateNewRainExceedance {
            get {
                return ResourceManager.GetString("CreateNewRainExceedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days prior to start.
        /// </summary>
        public static string DaysPriorToStart {
            get {
                return ResourceManager.GetString("DaysPriorToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email distribution list.
        /// </summary>
        public static string EmailDistributionList {
            get {
                return ResourceManager.GetString("EmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email distribution list to use.
        /// </summary>
        public static string EmailDistributionListToUse {
            get {
                return ResourceManager.GetString("EmailDistributionListToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find climate site within distance of rain exceedance.
        /// </summary>
        public static string FindClimateSitesWithinDistanceOfRainExceedance {
            get {
                return ResourceManager.GetString("FindClimateSitesWithinDistanceOfRainExceedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify on map.
        /// </summary>
        public static string IdentifyOnMap {
            get {
                return ResourceManager.GetString("IdentifyOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string Lng {
            get {
                return ResourceManager.GetString("Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and email list for partners.
        /// </summary>
        public static string NameAndEmailListForPartners {
            get {
                return ResourceManager.GetString("NameAndEmailListForPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and email list for staff.
        /// </summary>
        public static string NameAndEmailListForStaff {
            get {
                return ResourceManager.GetString("NameAndEmailListForStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only staff.
        /// </summary>
        public static string OnlyStaff {
            get {
                return ResourceManager.GetString("OnlyStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Staff Email Distribution List.
        /// </summary>
        public static string OnlyStaffEmailDistributionList {
            get {
                return ResourceManager.GetString("OnlyStaffEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open To.
        /// </summary>
        public static string OpenTo {
            get {
                return ResourceManager.GetString("OpenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain exceedance.
        /// </summary>
        public static string RainExceedance {
            get {
                return ResourceManager.GetString("RainExceedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain exceedance email distribution list.
        /// </summary>
        public static string RainExceedanceEmailDistributionList {
            get {
                return ResourceManager.GetString("RainExceedanceEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain Exceedance Name.
        /// </summary>
        public static string RainExceedanceName {
            get {
                return ResourceManager.GetString("RainExceedanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain extreme.
        /// </summary>
        public static string RainExtreme {
            get {
                return ResourceManager.GetString("RainExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain maximum.
        /// </summary>
        public static string RainMaximum {
            get {
                return ResourceManager.GetString("RainMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every year.
        /// </summary>
        public static string RepeatEveryYear {
            get {
                return ResourceManager.GetString("RepeatEveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select: Only Staff Email Distribution List.
        /// </summary>
        public static string SelectOnlyStaffEmailDistributionList {
            get {
                return ResourceManager.GetString("SelectOnlyStaffEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select: Stakeholders Email Distribution List.
        /// </summary>
        public static string SelectStakeholdersEmailDistributionList {
            get {
                return ResourceManager.GetString("SelectStakeholdersEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show climate sites.
        /// </summary>
        public static string ShowClimateSites {
            get {
                return ResourceManager.GetString("ShowClimateSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show climate sites on map.
        /// </summary>
        public static string ShowClimateSitesOnMap {
            get {
                return ResourceManager.GetString("ShowClimateSitesOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholders.
        /// </summary>
        public static string Stakeholders {
            get {
                return ResourceManager.GetString("Stakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholders Email Distribution List.
        /// </summary>
        public static string StakeholdersEmailDistributionList {
            get {
                return ResourceManager.GetString("StakeholdersEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To cancel edit just click on the green edit button.
        /// </summary>
        public static string ToCancelEditJustClickOnGreenEditButton {
            get {
                return ResourceManager.GetString("ToCancelEditJustClickOnGreenEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year round.
        /// </summary>
        public static string YearRound {
            get {
                return ResourceManager.GetString("YearRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might have to create the email distribution list before continuing.
        /// </summary>
        public static string YouMightHaveToCreateTheEmailDistributionListBeforeContinuing {
            get {
                return ResourceManager.GetString("YouMightHaveToCreateTheEmailDistributionListBeforeContinuing", resourceCulture);
            }
        }
    }
}
