//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.TVItem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TVItemViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVItemViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.TVItem.Resources.TVItemViewRes", typeof(TVItemViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sites.
        /// </summary>
        public static string AllSites {
            get {
                return ResourceManager.GetString("AllSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmbientSalinity  (PSU).
        /// </summary>
        public static string AmbientSalinity_PSU {
            get {
                return ResourceManager.GetString("AmbientSalinity_PSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Temperature (ºC).
        /// </summary>
        public static string AmbientTemperature_C {
            get {
                return ResourceManager.GetString("AmbientTemperature_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average flow.
        /// </summary>
        public static string AverageFlow {
            get {
                return ResourceManager.GetString("AverageFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Models.
        /// </summary>
        public static string BoxModels {
            get {
                return ResourceManager.GetString("BoxModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons help.
        /// </summary>
        public static string ButtonsHelp {
            get {
                return ResourceManager.GetString("ButtonsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently showing.
        /// </summary>
        public static string CurrentlyShowing {
            get {
                return ResourceManager.GetString("CurrentlyShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set.
        /// </summary>
        public static string DataSet {
            get {
                return ResourceManager.GetString("DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Factor (/day).
        /// </summary>
        public static string DecayFactor_per_day {
            get {
                return ResourceManager.GetString("DecayFactor_per_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Factor Amplitude.
        /// </summary>
        public static string DecayFactorAmplitude {
            get {
                return ResourceManager.GetString("DecayFactorAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Is Constant.
        /// </summary>
        public static string DecayIsConstant {
            get {
                return ResourceManager.GetString("DecayIsConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop reviewed.
        /// </summary>
        public static string DesktopReviewed {
            get {
                return ResourceManager.GetString("DesktopReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge.
        /// </summary>
        public static string Discharge {
            get {
                return ResourceManager.GetString("Discharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date And Time.
        /// </summary>
        public static string EndDateAndTime {
            get {
                return ResourceManager.GetString("EndDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date And Time Of Pollution.
        /// </summary>
        public static string EndDateAndTimeOfPollution {
            get {
                return ResourceManager.GetString("EndDateAndTimeOfPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        public static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic coordinates.
        /// </summary>
        public static string GeographicCoordinates {
            get {
                return ResourceManager.GetString("GeographicCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeographicCoordinatesDescriptionPopOver.
        /// </summary>
        public static string GeographicCoordinatesDescriptionPopOver {
            get {
                return ResourceManager.GetString("GeographicCoordinatesDescriptionPopOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Mean.
        /// </summary>
        public static string GeometricMean {
            get {
                return ResourceManager.GetString("GeometricMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrodynamic Result File Size.
        /// </summary>
        public static string HydroFileSize {
            get {
                return ResourceManager.GetString("HydroFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Continuous.
        /// </summary>
        public static string IsContinuous {
            get {
                return ResourceManager.GetString("IsContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not active.
        /// </summary>
        public static string IsNotActive {
            get {
                return ResourceManager.GetString("IsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sample date.
        /// </summary>
        public static string LastSampleDate {
            get {
                return ResourceManager.GetString("LastSampleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Classification.
        /// </summary>
        public static string LatestClassification {
            get {
                return ResourceManager.GetString("LatestClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Stations.
        /// </summary>
        public static string LiftStations {
            get {
                return ResourceManager.GetString("LiftStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate on map.
        /// </summary>
        public static string LocateOnMap {
            get {
                return ResourceManager.GetString("LocateOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manning Number.
        /// </summary>
        public static string ManningNumber {
            get {
                return ResourceManager.GetString("ManningNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum FC.
        /// </summary>
        public static string MaxFC {
            get {
                return ResourceManager.GetString("MaxFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike Scenarios.
        /// </summary>
        public static string MikeScenarios {
            get {
                return ResourceManager.GetString("MikeScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum FC.
        /// </summary>
        public static string MinFC {
            get {
                return ResourceManager.GetString("MinFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moving.
        /// </summary>
        public static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Statistics.
        /// </summary>
        public static string MovingStats {
            get {
                return ResourceManager.GetString("MovingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalities.
        /// </summary>
        public static string Municipalities {
            get {
                return ResourceManager.GetString("Municipalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs.
        /// </summary>
        public static string MWQMRuns {
            get {
                return ResourceManager.GetString("MWQMRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWQM Sites.
        /// </summary>
        public static string MWQMSites {
            get {
                return ResourceManager.GetString("MWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameDescriptionPopOver.
        /// </summary>
        public static string NameDescriptionPopOver {
            get {
                return ResourceManager.GetString("NameDescriptionPopOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No depuration.
        /// </summary>
        public static string NoDepuration {
            get {
                return ResourceManager.GetString("NoDepuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data.
        /// </summary>
        public static string NotEnoughData {
            get {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of issues.
        /// </summary>
        public static string NumberOfIssues {
            get {
                return ResourceManager.GetString("NumberOfIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Date.
        /// </summary>
        public static string ObservationDate {
            get {
                return ResourceManager.GetString("ObservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order By Date Modified.
        /// </summary>
        public static string OrderByDateModified {
            get {
                return ResourceManager.GetString("OrderByDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P90.
        /// </summary>
        public static string P90 {
            get {
                return ResourceManager.GetString("P90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathDescriptionPopOver.
        /// </summary>
        public static string PathDescriptionPopOver {
            get {
                return ResourceManager.GetString("PathDescriptionPopOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak flow.
        /// </summary>
        public static string PeakFlow {
            get {
                return ResourceManager.GetString("PeakFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of total flow.
        /// </summary>
        public static string PercentageTotalFlow {
            get {
                return ResourceManager.GetString("PercentageTotalFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Date and Time.
        /// </summary>
        public static string PollutionDateAndTime {
            get {
                return ResourceManager.GetString("PollutionDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Source Included.
        /// </summary>
        public static string PollutionSourceIncluded {
            get {
                return ResourceManager.GetString("PollutionSourceIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Source Not Included.
        /// </summary>
        public static string PollutionSourceNotIncluded {
            get {
                return ResourceManager.GetString("PollutionSourceNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Sources Sites.
        /// </summary>
        public static string PolSourceSites {
            get {
                return ResourceManager.GetString("PolSourceSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolygonDescriptionPopOver.
        /// </summary>
        public static string PolygonDescriptionPopOver {
            get {
                return ResourceManager.GetString("PolygonDescriptionPopOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces.
        /// </summary>
        public static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of samples with FC &gt; 260.
        /// </summary>
        public static string PSFCOver260 {
            get {
                return ResourceManager.GetString("PSFCOver260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of samples with FC &gt; 43.
        /// </summary>
        public static string PSFCOver43 {
            get {
                return ResourceManager.GetString("PSFCOver43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Frequency (minutes).
        /// </summary>
        public static string ResultFrequency_min {
            get {
                return ResourceManager.GetString("ResultFrequency_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        public static string Salinity {
            get {
                return ResourceManager.GetString("Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples Period.
        /// </summary>
        public static string SamplePeriod {
            get {
                return ResourceManager.GetString("SamplePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Description.
        /// </summary>
        public static string SelectedDescription {
            get {
                return ResourceManager.GetString("SelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Run Sample On Map.
        /// </summary>
        public static string ShowRunSampleOnMap {
            get {
                return ResourceManager.GetString("ShowRunSampleOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spills.
        /// </summary>
        public static string Spill {
            get {
                return ResourceManager.GetString("Spill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date And Time.
        /// </summary>
        public static string StartDateAndTime {
            get {
                return ResourceManager.GetString("StartDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date And Time Of Pollution.
        /// </summary>
        public static string StartDateAndTimeOfPollution {
            get {
                return ResourceManager.GetString("StartDateAndTimeOfPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Period.
        /// </summary>
        public static string StatsPeriod {
            get {
                return ResourceManager.GetString("StatsPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsectors.
        /// </summary>
        public static string Subsectors {
            get {
                return ResourceManager.GetString("Subsectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Transport Result File Size.
        /// </summary>
        public static string TransFileSize {
            get {
                return ResourceManager.GetString("TransFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of samples used for statistics.
        /// </summary>
        public static string UNSS {
            get {
                return ResourceManager.GetString("UNSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP Scenarios.
        /// </summary>
        public static string VPScenarios {
            get {
                return ResourceManager.GetString("VPScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction (degree).
        /// </summary>
        public static string WindDirection_deg {
            get {
                return ResourceManager.GetString("WindDirection_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed (km/h).
        /// </summary>
        public static string WindSpeed_km_h {
            get {
                return ResourceManager.GetString("WindSpeed_km_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Infrastructure.
        /// </summary>
        public static string WithInfrastructure {
            get {
                return ResourceManager.GetString("WithInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Infrastructure.
        /// </summary>
        public static string WithoutInfrastructure {
            get {
                return ResourceManager.GetString("WithoutInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Description.
        /// </summary>
        public static string WrittenDescription {
            get {
                return ResourceManager.GetString("WrittenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWTP.
        /// </summary>
        public static string WWTP {
            get {
                return ResourceManager.GetString("WWTP", resourceCulture);
            }
        }
    }
}
