//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfrastructureViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.Infrastructure.Resources.InfrastructureViewRes", typeof(InfrastructureViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aeration Type.
        /// </summary>
        public static string AerationType {
            get {
                return ResourceManager.GetString("AerationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm System Type.
        /// </summary>
        public static string AlarmSystemType {
            get {
                return ResourceManager.GetString("AlarmSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Growth Group.
        /// </summary>
        public static string AttachedGrowthGroup {
            get {
                return ResourceManager.GetString("AttachedGrowthGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Depth.
        /// </summary>
        public static string AverageDepth {
            get {
                return ResourceManager.GetString("AverageDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Flow.
        /// </summary>
        public static string AverageFlow {
            get {
                return ResourceManager.GetString("AverageFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel move.
        /// </summary>
        public static string CancelMove {
            get {
                return ResourceManager.GetString("CancelMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Overflow.
        /// </summary>
        public static string CanOverflow {
            get {
                return ResourceManager.GetString("CanOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Box Model and Visual Plumes.
        /// </summary>
        public static string CheckBoxModelandVisualPlumes {
            get {
                return ResourceManager.GetString("CheckBoxModelandVisualPlumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection System Type.
        /// </summary>
        public static string CollectionSystemType {
            get {
                return ResourceManager.GetString("CollectionSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load infrastructure info.
        /// </summary>
        public static string CouldNotLoadInfrastructureInfo {
            get {
                return ResourceManager.GetString("CouldNotLoadInfrastructureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Rate.
        /// </summary>
        public static string DecayRate {
            get {
                return ResourceManager.GetString("DecayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignFlow .
        /// </summary>
        public static string DesignFlow {
            get {
                return ResourceManager.GetString("DesignFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinfection Type.
        /// </summary>
        public static string DisinfectionType {
            get {
                return ResourceManager.GetString("DisinfectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance From Shore.
        /// </summary>
        public static string DistanceFromShore {
            get {
                return ResourceManager.GetString("DistanceFromShore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Type.
        /// </summary>
        public static string FacilityType {
            get {
                return ResourceManager.GetString("FacilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Type Not Lagoon Or Plant.
        /// </summary>
        public static string FacilityTypeNotLagoonOrPlant {
            get {
                return ResourceManager.GetString("FacilityTypeNotLagoonOrPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Field Velocity.
        /// </summary>
        public static string FarFieldVelocity {
            get {
                return ResourceManager.GetString("FarFieldVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flows or pumps into.
        /// </summary>
        public static string FlowsOrPumpsInto {
            get {
                return ResourceManager.GetString("FlowsOrPumpsInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has backup power.
        /// </summary>
        public static string HasBackupPower {
            get {
                return ResourceManager.GetString("HasBackupPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Angle.
        /// </summary>
        public static string HorizontalAngle {
            get {
                return ResourceManager.GetString("HorizontalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information below will be removed in the future.
        /// </summary>
        public static string InformationBelowWillBeRemovedInTheFuture {
            get {
                return ResourceManager.GetString("InformationBelowWillBeRemovedInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Coordinates.
        /// </summary>
        public static string InfrastructureCoordinates {
            get {
                return ResourceManager.GetString("InfrastructureCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Name.
        /// </summary>
        public static string InfrastructureName {
            get {
                return ResourceManager.GetString("InfrastructureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Outfall Coordinates.
        /// </summary>
        public static string InfrastructureOutfallCoordinates {
            get {
                return ResourceManager.GetString("InfrastructureOutfallCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure TVType Not Found.
        /// </summary>
        public static string InfrastructureTVTypeNotFound {
            get {
                return ResourceManager.GetString("InfrastructureTVTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Type.
        /// </summary>
        public static string InfrastructureType {
            get {
                return ResourceManager.GetString("InfrastructureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Data Comments.
        /// </summary>
        public static string InputDataComments {
            get {
                return ResourceManager.GetString("InputDataComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mechanically Aerated.
        /// </summary>
        public static string IsMechanicallyAerated {
            get {
                return ResourceManager.GetString("IsMechanicallyAerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Stations.
        /// </summary>
        public static string LiftStations {
            get {
                return ResourceManager.GetString("LiftStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Overflow.
        /// </summary>
        public static string LineOverflow {
            get {
                return ResourceManager.GetString("LineOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSID.
        /// </summary>
        public static string LSID {
            get {
                return ResourceManager.GetString("LSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move below.
        /// </summary>
        public static string MoveBelow {
            get {
                return ResourceManager.GetString("MoveBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to top.
        /// </summary>
        public static string MoveToTop {
            get {
                return ResourceManager.GetString("MoveToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Field Velocity.
        /// </summary>
        public static string NearFieldVelocity {
            get {
                return ResourceManager.GetString("NearFieldVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to select lagoon or plant.
        /// </summary>
        public static string NeedToSelectLagoonOrPlant {
            get {
                return ResourceManager.GetString("NeedToSelectLagoonOrPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Aerated Cells.
        /// </summary>
        public static string NumberOfAeratedCells {
            get {
                return ResourceManager.GetString("NumberOfAeratedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Cells.
        /// </summary>
        public static string NumberOfCells {
            get {
                return ResourceManager.GetString("NumberOfCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Ports.
        /// </summary>
        public static string NumberOfPorts {
            get {
                return ResourceManager.GetString("NumberOfPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfall.
        /// </summary>
        public static string Outfall {
            get {
                return ResourceManager.GetString("Outfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfall Latitude.
        /// </summary>
        public static string OutfallLatitude {
            get {
                return ResourceManager.GetString("OutfallLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfall Longitude.
        /// </summary>
        public static string OutfallLongitude {
            get {
                return ResourceManager.GetString("OutfallLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Flow.
        /// </summary>
        public static string PeakFlow {
            get {
                return ResourceManager.GetString("PeakFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Flow Of Total.
        /// </summary>
        public static string PercentFlowTotal {
            get {
                return ResourceManager.GetString("PercentFlowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population Served.
        /// </summary>
        public static string PopulationServed {
            get {
                return ResourceManager.GetString("PopulationServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Diameter.
        /// </summary>
        public static string PortDiameter {
            get {
                return ResourceManager.GetString("PortDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Elevation.
        /// </summary>
        public static string PortElevation {
            get {
                return ResourceManager.GetString("PortElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Spacing .
        /// </summary>
        public static string PortSpacing {
            get {
                return ResourceManager.GetString("PortSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Treatment Type.
        /// </summary>
        public static string PreliminaryTreatmentType {
            get {
                return ResourceManager.GetString("PreliminaryTreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Treatment Type.
        /// </summary>
        public static string PrimaryTreatmentType {
            get {
                return ResourceManager.GetString("PrimaryTreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrismID.
        /// </summary>
        public static string PrismID {
            get {
                return ResourceManager.GetString("PrismID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Water Concentration.
        /// </summary>
        public static string ReceivingWaterConc {
            get {
                return ResourceManager.GetString("ReceivingWaterConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Water Salinity .
        /// </summary>
        public static string ReceivingWaterSalinity {
            get {
                return ResourceManager.GetString("ReceivingWaterSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Water Temperature.
        /// </summary>
        public static string ReceivingWaterTemperature {
            get {
                return ResourceManager.GetString("ReceivingWaterTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Treatment Type.
        /// </summary>
        public static string SecondaryTreatmentType {
            get {
                return ResourceManager.GetString("SecondaryTreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See other municipality.
        /// </summary>
        public static string SeeOtherMunicipality {
            get {
                return ResourceManager.GetString("SeeOtherMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should use Facility Type etc... to replace this information.
        /// </summary>
        public static string ShouldUseFacilityTypeEtcToReplaceThisInformation {
            get {
                return ResourceManager.GetString("ShouldUseFacilityTypeEtcToReplaceThisInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map Item.
        /// </summary>
        public static string ShowMapItem {
            get {
                return ResourceManager.GetString("ShowMapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteID.
        /// </summary>
        public static string SiteID {
            get {
                return ResourceManager.GetString("SiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to move.
        /// </summary>
        public static string StartMove {
            get {
                return ResourceManager.GetString("StartMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended Growth Group.
        /// </summary>
        public static string SuspendedGrowthGroup {
            get {
                return ResourceManager.GetString("SuspendedGrowthGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Catch All Remove Later.
        /// </summary>
        public static string TempCatchRemoveLater {
            get {
                return ResourceManager.GetString("TempCatchRemoveLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary Treatment Type.
        /// </summary>
        public static string TertiaryTreatmentType {
            get {
                return ResourceManager.GetString("TertiaryTreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPID.
        /// </summary>
        public static string TPID {
            get {
                return ResourceManager.GetString("TPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Type.
        /// </summary>
        public static string TreatmentType {
            get {
                return ResourceManager.GetString("TreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve type.
        /// </summary>
        public static string ValveType {
            get {
                return ResourceManager.GetString("ValveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Angle.
        /// </summary>
        public static string VerticalAngle {
            get {
                return ResourceManager.GetString("VerticalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be removed.
        /// </summary>
        public static string WillBeRemoved {
            get {
                return ResourceManager.GetString("WillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWTP.
        /// </summary>
        public static string WWTPs {
            get {
                return ResourceManager.GetString("WWTPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
