//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.ProvinceTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProvinceToolsViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvinceToolsViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.ProvinceTools.Resources.ProvinceToolsViewRes", typeof(ProvinceToolsViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate site precipitation related tools.
        /// </summary>
        public static string ClimateSitePrecipitationRelatedTools {
            get {
                return ResourceManager.GetString("ClimateSitePrecipitationRelatedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill run precip by climate site priority for year.
        /// </summary>
        public static string FillRunPrecipByClimateSitePriorityForYear {
            get {
                return ResourceManager.GetString("FillRunPrecipByClimateSitePriorityForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find missing precip for province.
        /// </summary>
        public static string FindMissingPrecipForProvince {
            get {
                return ResourceManager.GetString("FindMissingPrecipForProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all precipitation for year.
        /// </summary>
        public static string GetAllPrecipitationForYear {
            get {
                return ResourceManager.GetString("GetAllPrecipitationForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder for more.
        /// </summary>
        public static string PlaceholderForMore {
            get {
                return ResourceManager.GetString("PlaceholderForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of these tasks can take a long time.
        /// </summary>
        public static string SomeOfTheseTasksCanTakeALongTime {
            get {
                return ResourceManager.GetString("SomeOfTheseTasksCanTakeALongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
