//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.SamplingPlan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SamplingPlanViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SamplingPlanViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.SamplingPlan.Resources.SamplingPlanViewRes", typeof(SamplingPlanViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1X.
        /// </summary>
        public static string _1X {
            get {
                return ResourceManager.GetString("_1X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2X.
        /// </summary>
        public static string _2X {
            get {
                return ResourceManager.GetString("_2X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.0 (˚C).
        /// </summary>
        public static string _35_0Celcius {
            get {
                return ResourceManager.GetString("_35_0Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.5 (˚C).
        /// </summary>
        public static string _44_5Celcius {
            get {
                return ResourceManager.GetString("_44_5Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 Media 1X.
        /// </summary>
        public static string A1Media1X {
            get {
                return ResourceManager.GetString("A1Media1X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 Media 2X.
        /// </summary>
        public static string A1Media2X {
            get {
                return ResourceManager.GetString("A1Media2X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 Fecal Coliform - Water Analysis Data Sheet.
        /// </summary>
        public static string A1SheetTitle {
            get {
                return ResourceManager.GetString("A1SheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Lab Sheet And Send Information To Data Base.
        /// </summary>
        public static string AcceptLabSheetAndSendInformationToDataBase {
            get {
                return ResourceManager.GetString("AcceptLabSheetAndSendInformationToDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code.
        /// </summary>
        public static string AccessCode {
            get {
                return ResourceManager.GetString("AccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sampling plans.
        /// </summary>
        public static string ActiveSamplingPlans {
            get {
                return ResourceManager.GetString("ActiveSamplingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyst.
        /// </summary>
        public static string Analyst {
            get {
                return ResourceManager.GetString("Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Method.
        /// </summary>
        public static string AnalyzeMethod {
            get {
                return ResourceManager.GetString("AnalyzeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        public static string ApprovalCode {
            get {
                return ResourceManager.GetString("ApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 14:00.
        /// </summary>
        public static string At14h {
            get {
                return ResourceManager.GetString("At14h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup directory.
        /// </summary>
        public static string BackupDirectory {
            get {
                return ResourceManager.GetString("BackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue text indicate value already in database.
        /// </summary>
        public static string BlueTextIndicateValueAlreadyInDatabase {
            get {
                return ResourceManager.GetString("BlueTextIndicateValueAlreadyInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated holding time (hours).
        /// </summary>
        public static string CalculatedHoldingTimeInHours {
            get {
                return ResourceManager.GetString("CalculatedHoldingTimeInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Incubation Time.
        /// </summary>
        public static string CalculatedIncubationTime {
            get {
                return ResourceManager.GetString("CalculatedIncubationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change run sampling type.
        /// </summary>
        public static string ChangeRunSamplingType {
            get {
                return ResourceManager.GetString("ChangeRunSamplingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the information above to change the sampling plan name.
        /// </summary>
        public static string ChangeTheInformationAboveToChangeTheSamplingPlanName {
            get {
                return ResourceManager.GetString("ChangeTheInformationAboveToChangeTheSamplingPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Lot #s.
        /// </summary>
        public static string ControlLotNumbs {
            get {
                return ResourceManager.GetString("ControlLotNumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sampling plan.
        /// </summary>
        public static string CreateSamplingPlan {
            get {
                return ResourceManager.GetString("CreateSamplingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + click to select multiple.
        /// </summary>
        public static string CtrlClickToSelectMultiple {
            get {
                return ResourceManager.GetString("CtrlClickToSelectMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily duplicate precision criteria.
        /// </summary>
        public static string DailyDuplicatePrecisionCriteria {
            get {
                return ResourceManager.GetString("DailyDuplicatePrecisionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where duplicate results differ in value, the higher result will be used in data computation..
        /// </summary>
        public static string DuplicateHighestValueWillBeUsedAndOtherValuesAsDuplicates {
            get {
                return ResourceManager.GetString("DuplicateHighestValueWillBeUsedAndOtherValuesAsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Information.
        /// </summary>
        public static string DuplicateInformation {
            get {
                return ResourceManager.GetString("DuplicateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Sampling plans.
        /// </summary>
        public static string ExistingSamplingPlans {
            get {
                return ResourceManager.GetString("ExistingSamplingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string ForGroupName {
            get {
                return ResourceManager.GetString("ForGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Value.
        /// </summary>
        public static string HasValue {
            get {
                return ResourceManager.GetString("HasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive or old sampling plans.
        /// </summary>
        public static string InactiveOrOldSamplingPlans {
            get {
                return ResourceManager.GetString("InactiveOrOldSamplingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include laboratory QA/QC.
        /// </summary>
        public static string IncludeLaboratoryQAQC {
            get {
                return ResourceManager.GetString("IncludeLaboratoryQAQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incubation Finish Time.
        /// </summary>
        public static string IncubationFinishTime {
            get {
                return ResourceManager.GetString("IncubationFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incubation started the same day.
        /// </summary>
        public static string IncubationStartedTheSameDay {
            get {
                return ResourceManager.GetString("IncubationStartedTheSameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incubation Start Time.
        /// </summary>
        public static string IncubationStartTime {
            get {
                return ResourceManager.GetString("IncubationStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intertech Duplicate Information.
        /// </summary>
        public static string IntertechDuplicateInformation {
            get {
                return ResourceManager.GetString("IntertechDuplicateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intertech duplicate precision criteria.
        /// </summary>
        public static string IntertechDuplicatePrecisionCriteria {
            get {
                return ResourceManager.GetString("IntertechDuplicatePrecisionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intertech Read Information.
        /// </summary>
        public static string IntertechReadInformation {
            get {
                return ResourceManager.GetString("IntertechReadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Contractor.
        /// </summary>
        public static string IsContractor {
            get {
                return ResourceManager.GetString("IsContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        public static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labsheet.
        /// </summary>
        public static string LabSheet {
            get {
                return ResourceManager.GetString("LabSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab sheets history.
        /// </summary>
        public static string LabSheetsHistory {
            get {
                return ResourceManager.GetString("LabSheetsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab sheets transferred.
        /// </summary>
        public static string LabSheetsTransferred {
            get {
                return ResourceManager.GetString("LabSheetsTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab sheets waiting to be accepted.
        /// </summary>
        public static string LabSheetsWaitingToBeAccepted {
            get {
                return ResourceManager.GetString("LabSheetsWaitingToBeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab sheet type.
        /// </summary>
        public static string LabSheetType {
            get {
                return ResourceManager.GetString("LabSheetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot #&apos;s.
        /// </summary>
        public static string LotNumbers {
            get {
                return ResourceManager.GetString("LotNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPN.
        /// </summary>
        public static string MPN {
            get {
                return ResourceManager.GetString("MPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWQM Sites.
        /// </summary>
        public static string MWQMSites {
            get {
                return ResourceManager.GetString("MWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N / A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative 35.
        /// </summary>
        public static string Negative35 {
            get {
                return ResourceManager.GetString("Negative35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative 44.5.
        /// </summary>
        public static string Negative44_5 {
            get {
                return ResourceManager.GetString("Negative44_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Target.
        /// </summary>
        public static string NonTarget {
            get {
                return ResourceManager.GetString("NonTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Target 35.
        /// </summary>
        public static string NonTarget35 {
            get {
                return ResourceManager.GetString("NonTarget35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Target 44.5.
        /// </summary>
        public static string NonTarget44_5 {
            get {
                return ResourceManager.GetString("NonTarget44_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need permission to setup Sampling plans..
        /// </summary>
        public static string NoPermissionMessageSamplingPlans {
            get {
                return ResourceManager.GetString("NoPermissionMessageSamplingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: All required information as per section 5.10.2 of ISO/IEC 17025 is available from the Laboratory Supervisor..
        /// </summary>
        public static string NotAllRequiredEtc {
            get {
                return ResourceManager.GetString("NotAllRequiredEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or 0 if not used.
        /// </summary>
        public static string OrZeroIfNotUsed {
            get {
                return ResourceManager.GetString("OrZeroIfNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 500.
        /// </summary>
        public static string Over500 {
            get {
                return ResourceManager.GetString("Over500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending approval.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive 35.
        /// </summary>
        public static string Positive35 {
            get {
                return ResourceManager.GetString("Positive35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive 44.5.
        /// </summary>
        public static string Positive44_5 {
            get {
                return ResourceManager.GetString("Positive44_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision Criteria.
        /// </summary>
        public static string PrecisionCriteria {
            get {
                return ResourceManager.GetString("PrecisionCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc. by.
        /// </summary>
        public static string ProcBy {
            get {
                return ResourceManager.GetString("ProcBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORDED TEMPERATURE IS ACTUAL READING + CORRECTION FACTOR.
        /// </summary>
        public static string RecordFactor {
            get {
                return ResourceManager.GetString("RecordFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Lab Sheet.
        /// </summary>
        public static string RejectLabSheet {
            get {
                return ResourceManager.GetString("RejectLabSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject reason.
        /// </summary>
        public static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Read By.
        /// </summary>
        public static string ResultsReadBy {
            get {
                return ResourceManager.GetString("ResultsReadBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Recorded By.
        /// </summary>
        public static string ResultsRecordedBy {
            get {
                return ResourceManager.GetString("ResultsRecordedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Log&apos;s.
        /// </summary>
        public static string RLogs {
            get {
                return ResourceManager.GetString("RLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Comment.
        /// </summary>
        public static string RunComment {
            get {
                return ResourceManager.GetString("RunComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs.
        /// </summary>
        public static string Runs {
            get {
                return ResourceManager.GetString("Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run weather comment.
        /// </summary>
        public static string RunWeatherComment {
            get {
                return ResourceManager.GetString("RunWeatherComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sal.
        /// </summary>
        public static string Sal {
            get {
                return ResourceManager.GetString("Sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity Read By.
        /// </summary>
        public static string SalinityReadBy {
            get {
                return ResourceManager.GetString("SalinityReadBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Bottle Lot #.
        /// </summary>
        public static string SampleBottleLotNumber {
            get {
                return ResourceManager.GetString("SampleBottleLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Crew.
        /// </summary>
        public static string SampleCrew {
            get {
                return ResourceManager.GetString("SampleCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample matrix.
        /// </summary>
        public static string SampleMatrix {
            get {
                return ResourceManager.GetString("SampleMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Time.
        /// </summary>
        public static string SampleTime {
            get {
                return ResourceManager.GetString("SampleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample type.
        /// </summary>
        public static string SampleType {
            get {
                return ResourceManager.GetString("SampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling plan name.
        /// </summary>
        public static string SamplingPlanName {
            get {
                return ResourceManager.GetString("SamplingPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling plan type.
        /// </summary>
        public static string SamplingPlanType {
            get {
                return ResourceManager.GetString("SamplingPlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the analyze method.
        /// </summary>
        public static string SelectTheAnalyzeMethod {
            get {
                return ResourceManager.GetString("SelectTheAnalyzeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the laboratory.
        /// </summary>
        public static string SelectTheLaboratory {
            get {
                return ResourceManager.GetString("SelectTheLaboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the sample matrix.
        /// </summary>
        public static string SelectTheSampleMatrix {
            get {
                return ResourceManager.GetString("SelectTheSampleMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up emails.
        /// </summary>
        public static string SettingUpEmails {
            get {
                return ResourceManager.GetString("SettingUpEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show historical lab sheets.
        /// </summary>
        public static string ShowHistoryLabSheets {
            get {
                return ResourceManager.GetString("ShowHistoryLabSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MWQM sites.
        /// </summary>
        public static string ShowMWQMSites {
            get {
                return ResourceManager.GetString("ShowMWQMSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Transferred Lab Sheets.
        /// </summary>
        public static string ShowTransferredLabSheets {
            get {
                return ResourceManager.GetString("ShowTransferredLabSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site #.
        /// </summary>
        public static string SiteNumber {
            get {
                return ResourceManager.GetString("SiteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsectors.
        /// </summary>
        public static string Subsectors {
            get {
                return ResourceManager.GetString("Subsectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T 0_1.
        /// </summary>
        public static string T0_1 {
            get {
                return ResourceManager.GetString("T0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T 1_0.
        /// </summary>
        public static string T1_0 {
            get {
                return ResourceManager.GetString("T1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T 10.
        /// </summary>
        public static string T10 {
            get {
                return ResourceManager.GetString("T10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC (˚C).
        /// </summary>
        public static string TCCelcius {
            get {
                return ResourceManager.GetString("TCCelcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Field.
        /// </summary>
        public static string TCField1 {
            get {
                return ResourceManager.GetString("TCField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Field #2.
        /// </summary>
        public static string TCField2 {
            get {
                return ResourceManager.GetString("TCField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC has 2 coolers.
        /// </summary>
        public static string TCHas2Coolers {
            get {
                return ResourceManager.GetString("TCHas2Coolers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Lab.
        /// </summary>
        public static string TCLab1 {
            get {
                return ResourceManager.GetString("TCLab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Lab #2.
        /// </summary>
        public static string TCLab2 {
            get {
                return ResourceManager.GetString("TCLab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tides.
        /// </summary>
        public static string Tides {
            get {
                return ResourceManager.GetString("Tides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ToGetPermissionMessage {
            get {
                return ResourceManager.GetString("ToGetPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To have access to Web tools information and applications please contact a site Administrator as listed below..
        /// </summary>
        public static string ToHaveAccess {
            get {
                return ResourceManager.GetString("ToHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string UnSelectAll {
            get {
                return ResourceManager.GetString("UnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual tube combination.
        /// </summary>
        public static string UnusualTubeCombination {
            get {
                return ResourceManager.GetString("UnusualTubeCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual tube combination, indentified by -999, exist in the lab sheet. Approving the lab sheet will NOT insert these (-999) values in the database..
        /// </summary>
        public static string UnusualTubeCombinationExistEtc {
            get {
                return ResourceManager.GetString("UnusualTubeCombinationExistEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Bath.
        /// </summary>
        public static string WaterBath {
            get {
                return ResourceManager.GetString("WaterBath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Comment.
        /// </summary>
        public static string WeatherComment {
            get {
                return ResourceManager.GetString("WeatherComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
