//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.File.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.File.Resources.FileViewRes", typeof(FileViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _fileEdit Returned Empty.
        /// </summary>
        public static string _fileEditReturnedEmpty {
            get {
                return ResourceManager.GetString("_fileEditReturnedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour Values.
        /// </summary>
        public static string ContourValues {
            get {
                return ResourceManager.GetString("ContourValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create document from templates.
        /// </summary>
        public static string CreateDocumentFromTemplates {
            get {
                return ResourceManager.GetString("CreateDocumentFromTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create document using parameters.
        /// </summary>
        public static string CreateDocumentUsingParameters {
            get {
                return ResourceManager.GetString("CreateDocumentUsingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        public static string CreatePDF {
            get {
                return ResourceManager.GetString("CreatePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) - Current vectors will be shown at the center of each element for which the path has a point in it..
        /// </summary>
        public static string CurrentVectorsWillBeShowAtTheCenterOfEachElementForWhichThePathHasAPointInIt {
            get {
                return ResourceManager.GetString("CurrentVectorsWillBeShowAtTheCenterOfEachElementForWhichThePathHasAPointInIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mode.
        /// </summary>
        public static string EditMode {
            get {
                return ResourceManager.GetString("EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting files to Arc GIS.
        /// </summary>
        public static string ExportingFilesToArcGIS {
            get {
                return ResourceManager.GetString("ExportingFilesToArcGIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File description.
        /// </summary>
        public static string FileDescription {
            get {
                return ResourceManager.GetString("FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generate Options.
        /// </summary>
        public static string FileGenerateOptions {
            get {
                return ResourceManager.GetString("FileGenerateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File purpose.
        /// </summary>
        public static string FilePurpose {
            get {
                return ResourceManager.GetString("FilePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each 10 cm/s show vector length.
        /// </summary>
        public static string ForEach10cm_sShowVectorLength {
            get {
                return ResourceManager.GetString("ForEach10cm_sShowVectorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Water.
        /// </summary>
        public static string FromWater {
            get {
                return ResourceManager.GetString("FromWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented.
        /// </summary>
        public static string Implemented {
            get {
                return ResourceManager.GetString("Implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in meters (approx.).
        /// </summary>
        public static string inMetersApprox {
            get {
                return ResourceManager.GetString("inMetersApprox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep file name.
        /// </summary>
        public static string KeepFileName {
            get {
                return ResourceManager.GetString("KeepFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Stations.
        /// </summary>
        public static string LiftStations {
            get {
                return ResourceManager.GetString("LiftStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Sites.
        /// </summary>
        public static string MonitoringSites {
            get {
                return ResourceManager.GetString("MonitoringSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalities.
        /// </summary>
        public static string Municipalities {
            get {
                return ResourceManager.GetString("Municipalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no extension.
        /// </summary>
        public static string NoExtension {
            get {
                return ResourceManager.GetString("NoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Source Sites.
        /// </summary>
        public static string PollutionSourceSites {
            get {
                return ResourceManager.GetString("PollutionSourceSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + click to select many.
        /// </summary>
        public static string PressCtrlAndClickToSelectMany {
            get {
                return ResourceManager.GetString("PressCtrlAndClickToSelectMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) - Replace the text within this box by copying a Google Earth Path..
        /// </summary>
        public static string ReplaceTheTextWithinBoxByCopyingAGoogleEarthPath {
            get {
                return ResourceManager.GetString("ReplaceTheTextWithinBoxByCopyingAGoogleEarthPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as file name.
        /// </summary>
        public static string SaveAsFileName {
            get {
                return ResourceManager.GetString("SaveAsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all [Ctrl + A] Paste [Ctrl-V].
        /// </summary>
        public static string SelectAllCtrlAPasteCtrlV {
            get {
                return ResourceManager.GetString("SelectAllCtrlAPasteCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide tag list.
        /// </summary>
        public static string ShowOrHideTagList {
            get {
                return ResourceManager.GetString("ShowOrHideTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsector Pollution Source Field Sheet.
        /// </summary>
        public static string SubsectorPollutionSourceFieldSheet {
            get {
                return ResourceManager.GetString("SubsectorPollutionSourceFieldSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task running.
        /// </summary>
        public static string TaskRunning {
            get {
                return ResourceManager.GetString("TaskRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template example.
        /// </summary>
        public static string TemplateExample {
            get {
                return ResourceManager.GetString("TemplateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use parent coordinates.
        /// </summary>
        public static string UseParentCoordinates {
            get {
                return ResourceManager.GetString("UseParentCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWTP.
        /// </summary>
        public static string WWTP {
            get {
                return ResourceManager.GetString("WWTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of document.
        /// </summary>
        public static string YearOfDocument {
            get {
                return ResourceManager.GetString("YearOfDocument", resourceCulture);
            }
        }
    }
}
