//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.Home.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.Home.Resources.HomeViewRes", typeof(HomeViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSP.
        /// </summary>
        public static string CSSP {
            get {
                return ResourceManager.GetString("CSSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Shellfish Sanitation Program.
        /// </summary>
        public static string CSSP_FULL {
            get {
                return ResourceManager.GetString("CSSP_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSP Web Tools.
        /// </summary>
        public static string CSSPWebTools {
            get {
                return ResourceManager.GetString("CSSPWebTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        public static string DeleteAppTask {
            get {
                return ResourceManager.GetString("DeleteAppTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get permission.
        /// </summary>
        public static string GetPermission {
            get {
                return ResourceManager.GetString("GetPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web tools will let you:.
        /// </summary>
        public static string List10HAppVarFunc {
            get {
                return ResourceManager.GetString("List10HAppVarFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view and update the waste water treatment plants and the lift stations information,.
        /// </summary>
        public static string List11ContainInfo {
            get {
                return ResourceManager.GetString("List11ContainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make calculation using Box Model and Visual Plumes, .
        /// </summary>
        public static string List12BoxModel {
            get {
                return ResourceManager.GetString("List12BoxModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run various scenarios for existing MIKE 21/3 setup scenarios and store results, and finally.
        /// </summary>
        public static string List13Mike {
            get {
                return ResourceManager.GetString("List13Mike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage the information of MWQM..
        /// </summary>
        public static string List14MWQMInformationManagement {
            get {
                return ResourceManager.GetString("List14MWQMInformationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and Register.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine Water Quality Monitoring.
        /// </summary>
        public static string MWQM_FULL {
            get {
                return ResourceManager.GetString("MWQM_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission required to get access.
        /// </summary>
        public static string PermissionRequiredToGetAccess {
            get {
                return ResourceManager.GetString("PermissionRequiredToGetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or register in order to access CSSP Web Tools and documentation.
        /// </summary>
        public static string PleaseLoginRegisterAccessMessage {
            get {
                return ResourceManager.GetString("PleaseLoginRegisterAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Auto Refresh.
        /// </summary>
        public static string RestartAutoRefresh {
            get {
                return ResourceManager.GetString("RestartAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Plans.
        /// </summary>
        public static string SamplingPlans {
            get {
                return ResourceManager.GetString("SamplingPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start using CSSP - Web Tools.
        /// </summary>
        public static string StartUsingCSSPWebTools {
            get {
                return ResourceManager.GetString("StartUsingCSSPWebTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Auto Refresh.
        /// </summary>
        public static string StopAutoRefresh {
            get {
                return ResourceManager.GetString("StopAutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks running.
        /// </summary>
        public static string TasksRunning {
            get {
                return ResourceManager.GetString("TasksRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To have access to Web tools information and applications please contact a site Administrator as listed below..
        /// </summary>
        public static string ToHaveAccess {
            get {
                return ResourceManager.GetString("ToHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update details.
        /// </summary>
        public static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will refresh in.
        /// </summary>
        public static string WillRefreshIn {
            get {
                return ResourceManager.GetString("WillRefreshIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently do not have the authorization to browse this information..
        /// </summary>
        public static string YouCurrentlyDoNotHavePermission {
            get {
                return ResourceManager.GetString("YouCurrentlyDoNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your permission.
        /// </summary>
        public static string YourPermission {
            get {
                return ResourceManager.GetString("YourPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status.
        /// </summary>
        public static string YourStatus {
            get {
                return ResourceManager.GetString("YourStatus", resourceCulture);
            }
        }
    }
}
