//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.EmailDistributionList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailDistributionListViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailDistributionListViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.EmailDistributionList.Resources.EmailDistributionListViewRes", typeof(EmailDistributionListViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new email distribution list.
        /// </summary>
        public static string AddANewEmailDistributionList {
            get {
                return ResourceManager.GetString("AddANewEmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new contact.
        /// </summary>
        public static string AddNewContact {
            get {
                return ResourceManager.GetString("AddNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the edit button to create or modify lists as well as generate Excel document.
        /// </summary>
        public static string ClickTheEditButtonToCreateOrModifyListsAsWellAsGenerateExcelDocument {
            get {
                return ResourceManager.GetString("ClickTheEditButtonToCreateOrModifyListsAsWellAsGenerateExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMP.
        /// </summary>
        public static string CMP {
            get {
                return ResourceManager.GetString("CMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMP rainfall seasonal.
        /// </summary>
        public static string CMPRainfallSeasonal {
            get {
                return ResourceManager.GetString("CMPRainfallSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMP wastewater.
        /// </summary>
        public static string CMPWastewater {
            get {
                return ResourceManager.GetString("CMPWastewater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email distributions lists.
        /// </summary>
        public static string EmailDistributionList {
            get {
                return ResourceManager.GetString("EmailDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency wastewater.
        /// </summary>
        public static string EmergencyWastewater {
            get {
                return ResourceManager.GetString("EmergencyWastewater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency weather.
        /// </summary>
        public static string EmergencyWeather {
            get {
                return ResourceManager.GetString("EmergencyWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export lists to shared drive.
        /// </summary>
        public static string ExportListsToSharedDrive {
            get {
                return ResourceManager.GetString("ExportListsToSharedDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate excel file then look under file tab once done.
        /// </summary>
        public static string GenerateExcelFileThenLookUnderFileTabOnceDone {
            get {
                return ResourceManager.GetString("GenerateExcelFileThenLookUnderFileTabOnceDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform individual on.
        /// </summary>
        public static string InformIndividualOn {
            get {
                return ResourceManager.GetString("InformIndividualOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is cc.
        /// </summary>
        public static string IsCC {
            get {
                return ResourceManager.GetString("IsCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall.
        /// </summary>
        public static string Rainfall {
            get {
                return ResourceManager.GetString("Rainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopening.
        /// </summary>
        public static string Reopening {
            get {
                return ResourceManager.GetString("Reopening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopening all types.
        /// </summary>
        public static string ReopeningAllTypes {
            get {
                return ResourceManager.GetString("ReopeningAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        public static string Seasonal {
            get {
                return ResourceManager.GetString("Seasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide add.
        /// </summary>
        public static string ShowHideAdd {
            get {
                return ResourceManager.GetString("ShowHideAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wastewater.
        /// </summary>
        public static string Wastewater {
            get {
                return ResourceManager.GetString("Wastewater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
    }
}
