//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.BoxModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoxModelViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoxModelViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.BoxModel.Resources.BoxModelViewRes", typeof(BoxModelViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Model Calculated Results.
        /// </summary>
        public static string BoxModelCalculatedResult {
            get {
                return ResourceManager.GetString("BoxModelCalculatedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string CalculatedRadius {
            get {
                return ResourceManager.GetString("CalculatedRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string CalculatedSurface {
            get {
                return ResourceManager.GetString("CalculatedSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string CalculatedVolume {
            get {
                return ResourceManager.GetString("CalculatedVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration objective.
        /// </summary>
        public static string ConcentrationObjective {
            get {
                return ResourceManager.GetString("ConcentrationObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay, pre-disinfection.
        /// </summary>
        public static string DecayPreDisinfection {
            get {
                return ResourceManager.GetString("DecayPreDisinfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay rate.
        /// </summary>
        public static string DecayRate {
            get {
                return ResourceManager.GetString("DecayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay, untreated.
        /// </summary>
        public static string DecayUntreated {
            get {
                return ResourceManager.GetString("DecayUntreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilution.
        /// </summary>
        public static string Dilution {
            get {
                return ResourceManager.GetString("Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge.
        /// </summary>
        public static string Discharge {
            get {
                return ResourceManager.GetString("Discharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge duration.
        /// </summary>
        public static string DischargeDuration {
            get {
                return ResourceManager.GetString("DischargeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        public static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecal Coliforms.
        /// </summary>
        public static string FC_Full {
            get {
                return ResourceManager.GetString("FC_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed length.
        /// </summary>
        public static string FixedLength {
            get {
                return ResourceManager.GetString("FixedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed width.
        /// </summary>
        public static string FixedWidth {
            get {
                return ResourceManager.GetString("FixedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed length and width is selected.
        /// </summary>
        public static string FixLengthAndFixWidthAreSelected {
            get {
                return ResourceManager.GetString("FixLengthAndFixWidthAreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string hours_abbr {
            get {
                return ResourceManager.GetString("hours_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input information.
        /// </summary>
        public static string InputInformation {
            get {
                return ResourceManager.GetString("InputInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is required when fixed length is selected.
        /// </summary>
        public static string LengthRequiredWhenFixLengthSelected {
            get {
                return ResourceManager.GetString("LengthRequiredWhenFixLengthSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No decay, pre-disinfection.
        /// </summary>
        public static string NoDecayPreDisinfection {
            get {
                return ResourceManager.GetString("NoDecayPreDisinfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No decay, untreated.
        /// </summary>
        public static string NoDecayUntreated {
            get {
                return ResourceManager.GetString("NoDecayUntreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item.
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one.
        /// </summary>
        public static string PleaseSelectOnlyOne {
            get {
                return ResourceManager.GetString("PleaseSelectOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-disinfection.
        /// </summary>
        public static string PreDisinfection {
            get {
                return ResourceManager.GetString("PreDisinfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario name.
        /// </summary>
        public static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi circle.
        /// </summary>
        public static string SemiCircle {
            get {
                return ResourceManager.GetString("SemiCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T90.
        /// </summary>
        public static string T90 {
            get {
                return ResourceManager.GetString("T90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /day.
        /// </summary>
        public static string unitPerDay {
            get {
                return ResourceManager.GetString("unitPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untreated.
        /// </summary>
        public static string Untreated {
            get {
                return ResourceManager.GetString("Untreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width is required when fixed width is selected.
        /// </summary>
        public static string WidthRequiredWhenFixWidthSelected {
            get {
                return ResourceManager.GetString("WidthRequiredWhenFixWidthSelected", resourceCulture);
            }
        }
    }
}
