//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.ClimateSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClimateSiteViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClimateSiteViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.ClimateSite.Resources.ClimateSiteViewRes", typeof(ClimateSiteViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dash [-] between two years represent: from year to year inclusively.
        /// </summary>
        public static string ADashBetweenTwoYearsRepresentFromYearToYearInclusively {
            get {
                return ResourceManager.GetString("ADashBetweenTwoYearsRepresentFromYearToYearInclusively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any space will be omitted.
        /// </summary>
        public static string AnySpaceWillBeOmitted {
            get {
                return ResourceManager.GetString("AnySpaceWillBeOmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything unrecognized - the user will receive an error message.
        /// </summary>
        public static string AnythingUnrecognizedTheUserWillReceiveAnErrorMessage {
            get {
                return ResourceManager.GetString("AnythingUnrecognizedTheUserWillReceiveAnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A year between two commas represent that year.
        /// </summary>
        public static string AYearBetweenTwoCommasRepresentThatYear {
            get {
                return ResourceManager.GetString("AYearBetweenTwoCommasRepresentThatYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on globe icon to view on map.
        /// </summary>
        public static string ClickOnGlobeIconToViewOnMap {
            get {
                return ResourceManager.GetString("ClickOnGlobeIconToViewOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate site.
        /// </summary>
        public static string ClimateSite {
            get {
                return ResourceManager.GetString("ClimateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Site Name.
        /// </summary>
        public static string ClimateSiteName {
            get {
                return ResourceManager.GetString("ClimateSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites and years of use.
        /// </summary>
        public static string ClimateSitesAndYearsOfUse {
            get {
                return ResourceManager.GetString("ClimateSitesAndYearsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites data for each run.
        /// </summary>
        public static string ClimateSitesDataForEachRun {
            get {
                return ResourceManager.GetString("ClimateSitesDataForEachRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites priorities.
        /// </summary>
        public static string ClimateSitesPriorities {
            get {
                return ResourceManager.GetString("ClimateSitesPriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites to use for subsector.
        /// </summary>
        public static string ClimateSitesToUseForSubsector {
            get {
                return ResourceManager.GetString("ClimateSitesToUseForSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites to use for subsector verify and save.
        /// </summary>
        public static string ClimateSitesToUseForSubsectorVerifyAndSave {
            get {
                return ResourceManager.GetString("ClimateSitesToUseForSubsectorVerifyAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate sites used and within distance.
        /// </summary>
        public static string ClimateSitesUsedAndWithinDistance {
            get {
                return ResourceManager.GetString("ClimateSitesUsedAndWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending with a dash [-] represent up to current year.
        /// </summary>
        public static string EndingWithADashRepresentUpToCurrentYear {
            get {
                return ResourceManager.GetString("EndingWithADashRepresentUpToCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered.
        /// </summary>
        public static string Entered {
            get {
                return ResourceManager.GetString("Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill using.
        /// </summary>
        public static string FillUsing {
            get {
                return ResourceManager.GetString("FillUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find climate sites within distance of subsector.
        /// </summary>
        public static string FindClimateSitesWithinDistanceOfSubsector {
            get {
                return ResourceManager.GetString("FindClimateSitesWithinDistanceOfSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get climate data for runs of year {0}.
        /// </summary>
        public static string GetClimateDataForRunsOfYear_ {
            get {
                return ResourceManager.GetString("GetClimateDataForRunsOfYear_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has runs.
        /// </summary>
        public static string HasRuns {
            get {
                return ResourceManager.GetString("HasRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify on map.
        /// </summary>
        public static string IdentifyOnMap {
            get {
                return ResourceManager.GetString("IdentifyOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load CoCoRaHS data.
        /// </summary>
        public static string LoadCoCoRaHSData {
            get {
                return ResourceManager.GetString("LoadCoCoRaHSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Temperature (˚C).
        /// </summary>
        public static string MaxTemp_C {
            get {
                return ResourceManager.GetString("MaxTemp_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Temperature (˚C).
        /// </summary>
        public static string MinTemp_C {
            get {
                return ResourceManager.GetString("MinTemp_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data on MSC historical site.
        /// </summary>
        public static string NoDataOnMSCHistoricalSite {
            get {
                return ResourceManager.GetString("NoDataOnMSCHistoricalSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only need to be done once if new data exist on CoCoRaHS web site.
        /// </summary>
        public static string OnlyNeedToBeDoneOnceIfNewDataExistOnCocoRaHSWebSite {
            get {
                return ResourceManager.GetString("OnlyNeedToBeDoneOnceIfNewDataExistOnCocoRaHSWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period with daily data.
        /// </summary>
        public static string PeriodWithDailyData {
            get {
                return ResourceManager.GetString("PeriodWithDailyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall (mm).
        /// </summary>
        public static string Rainfall_mm {
            get {
                return ResourceManager.GetString("Rainfall_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall Manually Entered (mm).
        /// </summary>
        public static string RainfallEntered_mm {
            get {
                return ResourceManager.GetString("RainfallEntered_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save button at bottom of page.
        /// </summary>
        public static string SaveButtonAtBottomOfPage {
            get {
                return ResourceManager.GetString("SaveButtonAtBottomOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save climate site priorities.
        /// </summary>
        public static string SaveClimateSitePriorities {
            get {
                return ResourceManager.GetString("SaveClimateSitePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save entered precipitation.
        /// </summary>
        public static string SaveEnteredPrecipitation {
            get {
                return ResourceManager.GetString("SaveEnteredPrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an adjacent subsector.
        /// </summary>
        public static string SelectAnAdjacentSubsector {
            get {
                return ResourceManager.GetString("SelectAnAdjacentSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a run above to see precipitation.
        /// </summary>
        public static string SelectARunAboveToSeePrecipitation {
            get {
                return ResourceManager.GetString("SelectARunAboveToSeePrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set climate site priority by distance.
        /// </summary>
        public static string SetClimateSitePriorityByDistance {
            get {
                return ResourceManager.GetString("SetClimateSitePriorityByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data to use by average for year {0}.
        /// </summary>
        public static string SetDataToUseByAverageForYear_ {
            get {
                return ResourceManager.GetString("SetDataToUseByAverageForYear_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data to use by priority for year {0}.
        /// </summary>
        public static string SetDataToUseByPriorityForYear_ {
            get {
                return ResourceManager.GetString("SetDataToUseByPriorityForYear_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting climate site priorities.
        /// </summary>
        public static string SettingClimateSitePriorities {
            get {
                return ResourceManager.GetString("SettingClimateSitePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show climate sites on map.
        /// </summary>
        public static string ShowClimateSitesOnMap {
            get {
                return ResourceManager.GetString("ShowClimateSitesOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow (cm).
        /// </summary>
        public static string Snow_cm {
            get {
                return ResourceManager.GetString("Snow_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow On Ground (cm).
        /// </summary>
        public static string SnowOnGround_cm {
            get {
                return ResourceManager.GetString("SnowOnGround_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsector runs.
        /// </summary>
        public static string SubsectorRuns {
            get {
                return ResourceManager.GetString("SubsectorRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Precipitation (rain[mm] and/or snow[cm]).
        /// </summary>
        public static string TotalPrecip_mm_cm {
            get {
                return ResourceManager.GetString("TotalPrecip_mm_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use same climate sites as selected subsector.
        /// </summary>
        public static string UseSameClimateSitesAsSelectedSubsector {
            get {
                return ResourceManager.GetString("UseSameClimateSitesAsSelectedSubsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values to be used.
        /// </summary>
        public static string ValuesToBeUsed {
            get {
                return ResourceManager.GetString("ValuesToBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data Type.
        /// </summary>
        public static string ViewDataType {
            get {
                return ResourceManager.GetString("ViewDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        public static string Weighted {
            get {
                return ResourceManager.GetString("Weighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of use.
        /// </summary>
        public static string YearsOfUse {
            get {
                return ResourceManager.GetString("YearsOfUse", resourceCulture);
            }
        }
    }
}
