//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.MikeScenario.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MikeScenarioViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MikeScenarioViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.MikeScenario.Resources.MikeScenarioViewRes", typeof(MikeScenarioViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept WebTide Boundary Conditions.
        /// </summary>
        public static string AcceptWebTideBoundaryCondition {
            get {
                return ResourceManager.GetString("AcceptWebTideBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an effluent.
        /// </summary>
        public static string AddEffluent {
            get {
                return ResourceManager.GetString("AddEffluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mike Scenario.
        /// </summary>
        public static string AddMikeScenario {
            get {
                return ResourceManager.GetString("AddMikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Mike Scenario.
        /// </summary>
        public static string AddNewMikeScenario {
            get {
                return ResourceManager.GetString("AddNewMikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new source.
        /// </summary>
        public static string AddNewSource {
            get {
                return ResourceManager.GetString("AddNewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All web tides below need to be generated accordingly.
        /// </summary>
        public static string AllWebTidesBelowToGenerate {
            get {
                return ResourceManager.GetString("AllWebTidesBelowToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient salinity.
        /// </summary>
        public static string AmbientSalinity {
            get {
                return ResourceManager.GetString("AmbientSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient temperature.
        /// </summary>
        public static string AmbientTemperature {
            get {
                return ResourceManager.GetString("AmbientTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask to run.
        /// </summary>
        public static string AskToRun {
            get {
                return ResourceManager.GetString("AskToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization is needed.
        /// </summary>
        public static string AuthorizationNeeded {
            get {
                return ResourceManager.GetString("AuthorizationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning.
        /// </summary>
        public static string Beginning {
            get {
                return ResourceManager.GetString("Beginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Conditions.
        /// </summary>
        public static string BoundaryCondition {
            get {
                return ResourceManager.GetString("BoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Conditions Nodes.
        /// </summary>
        public static string BoundaryConditionNodes {
            get {
                return ResourceManager.GetString("BoundaryConditionNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Conditions.
        /// </summary>
        public static string BoundaryConditions {
            get {
                return ResourceManager.GetString("BoundaryConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelNewSource {
            get {
                return ResourceManager.GetString("CancelNewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Task.
        /// </summary>
        public static string CancelTask {
            get {
                return ResourceManager.GetString("CancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Map.
        /// </summary>
        public static string ClearMap {
            get {
                return ResourceManager.GetString("ClearMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create water level boundary condition for WebTide first node.
        /// </summary>
        public static string CreateWaterLevelBoundaryConditionForWebTideFirstNode {
            get {
                return ResourceManager.GetString("CreateWaterLevelBoundaryConditionForWebTideFirstNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date (UTC).
        /// </summary>
        public static string DateNameUnit {
            get {
                return ResourceManager.GetString("DateNameUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay is constant.
        /// </summary>
        public static string DecayConstant {
            get {
                return ResourceManager.GetString("DecayConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay factor amplitude.
        /// </summary>
        public static string DecayFactorAmplitude {
            get {
                return ResourceManager.GetString("DecayFactorAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay factor average.
        /// </summary>
        public static string DecayFactorAverage {
            get {
                return ResourceManager.GetString("DecayFactorAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degree.
        /// </summary>
        public static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        public static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this source.
        /// </summary>
        public static string DeleteSource {
            get {
                return ResourceManager.GetString("DeleteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc.
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drainage area (km2).
        /// </summary>
        public static string DrainageArea_km2 {
            get {
                return ResourceManager.GetString("DrainageArea_km2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string East_abr {
            get {
                return ResourceManager.GetString("East_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent.
        /// </summary>
        public static string Effluent {
            get {
                return ResourceManager.GetString("Effluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent Finish.
        /// </summary>
        public static string EffluentFinish {
            get {
                return ResourceManager.GetString("EffluentFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluents.
        /// </summary>
        public static string Effluents {
            get {
                return ResourceManager.GetString("Effluents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent Start.
        /// </summary>
        public static string EffluentStart {
            get {
                return ResourceManager.GetString("EffluentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date and Time.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Flow.
        /// </summary>
        public static string EndFlow {
            get {
                return ResourceManager.GetString("EndFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        public static string Ending {
            get {
                return ResourceManager.GetString("Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Pollution.
        /// </summary>
        public static string EndPollution {
            get {
                return ResourceManager.GetString("EndPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Salinity.
        /// </summary>
        public static string EndSalinity {
            get {
                return ResourceManager.GetString("EndSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Temperature.
        /// </summary>
        public static string EndTemperature {
            get {
                return ResourceManager.GetString("EndTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating page.
        /// </summary>
        public static string ErrorWhileCreatingPage {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faecal Coliform.
        /// </summary>
        public static string FecalColiform {
            get {
                return ResourceManager.GetString("FecalColiform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File full path.
        /// </summary>
        public static string FileFullPath {
            get {
                return ResourceManager.GetString("FileFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileNameLabel {
            get {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For simulating MWQM Run.
        /// </summary>
        public static string ForSimulatingMWQMRun {
            get {
                return ResourceManager.GetString("ForSimulatingMWQMRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Parameters.
        /// </summary>
        public static string GeneralParameters {
            get {
                return ResourceManager.GetString("GeneralParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate decoupling files.
        /// </summary>
        public static string GenerateDecouplingFiles {
            get {
                return ResourceManager.GetString("GenerateDecouplingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Web Tide Nodes.
        /// </summary>
        public static string GenerateWebTideNodes {
            get {
                return ResourceManager.GetString("GenerateWebTideNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get drainage area.
        /// </summary>
        public static string GetDrainageArea {
            get {
                return ResourceManager.GetString("GetDrainageArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get factor.
        /// </summary>
        public static string GetFactor {
            get {
                return ResourceManager.GetString("GetFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting other files to upload.
        /// </summary>
        public static string GettingOtherFilesToUpload {
            get {
                return ResourceManager.GetString("GettingOtherFilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string HourUnit {
            get {
                return ResourceManager.GetString("HourUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrometric.
        /// </summary>
        public static string Hydrometric {
            get {
                return ResourceManager.GetString("Hydrometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in scenario.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Infrastructure.
        /// </summary>
        public static string IncludedInfrastructure {
            get {
                return ResourceManager.GetString("IncludedInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included Pollution Source.
        /// </summary>
        public static string IncludedPollutionSource {
            get {
                return ResourceManager.GetString("IncludedPollutionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included River.
        /// </summary>
        public static string IncludedRiver {
            get {
                return ResourceManager.GetString("IncludedRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files.
        /// </summary>
        public static string InputFiles {
            get {
                return ResourceManager.GetString("InputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Summary.
        /// </summary>
        public static string InputSummary {
            get {
                return ResourceManager.GetString("InputSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is continuous.
        /// </summary>
        public static string IsContinuous {
            get {
                return ResourceManager.GetString("IsContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is included.
        /// </summary>
        public static string IsIncluded {
            get {
                return ResourceManager.GetString("IsIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not continuous.
        /// </summary>
        public static string IsNotContinuous {
            get {
                return ResourceManager.GetString("IsNotContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not river.
        /// </summary>
        public static string IsNotRiver {
            get {
                return ResourceManager.GetString("IsNotRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is river.
        /// </summary>
        public static string IsRiver {
            get {
                return ResourceManager.GetString("IsRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Lat {
            get {
                return ResourceManager.GetString("Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string LatitudeLongitude {
            get {
                return ResourceManager.GetString("LatitudeLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string Lng {
            get {
                return ResourceManager.GetString("Lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local time.
        /// </summary>
        public static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manning number.
        /// </summary>
        public static string ManningNumber {
            get {
                return ResourceManager.GetString("ManningNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE Scenario.
        /// </summary>
        public static string MikeScenario {
            get {
                return ResourceManager.GetString("MikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike Scenario Period.
        /// </summary>
        public static string MikeScenarioPeriod {
            get {
                return ResourceManager.GetString("MikeScenarioPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mike Source Information.
        /// </summary>
        public static string MikeSourceInformation {
            get {
                return ResourceManager.GetString("MikeSourceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPN.
        /// </summary>
        public static string MostProbableNumber_abr {
            get {
                return ResourceManager.GetString("MostProbableNumber_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWQM run dates.
        /// </summary>
        public static string MWQMRunDates {
            get {
                return ResourceManager.GetString("MWQMRunDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hydrometric site available for selection.
        /// </summary>
        public static string NoHydrometricSiteAvailableForSelection {
            get {
                return ResourceManager.GetString("NoHydrometricSiteAvailableForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string North_abr {
            get {
                return ResourceManager.GetString("North_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented Yet.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Included.
        /// </summary>
        public static string NotIncluded {
            get {
                return ResourceManager.GetString("NotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not this file.
        /// </summary>
        public static string NotThisFile {
            get {
                return ResourceManager.GetString("NotThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other file to upload.
        /// </summary>
        public static string OtherFileToUpload {
            get {
                return ResourceManager.GetString("OtherFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Parameters.
        /// </summary>
        public static string OutputParameters {
            get {
                return ResourceManager.GetString("OutputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string perday {
            get {
                return ResourceManager.GetString("perday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete setup.
        /// </summary>
        public static string PleaseCompleteSetup {
            get {
                return ResourceManager.GetString("PleaseCompleteSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution.
        /// </summary>
        public static string Pollution {
            get {
                return ResourceManager.GetString("Pollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading.
        /// </summary>
        public static string Reloading {
            get {
                return ResourceManager.GetString("Reloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset WebTide.
        /// </summary>
        public static string ResetWebTide {
            get {
                return ResourceManager.GetString("ResetWebTide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results frequency.
        /// </summary>
        public static string ResultFrequency {
            get {
                return ResourceManager.GetString("ResultFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        public static string Salinity {
            get {
                return ResourceManager.GetString("Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveEffluent {
            get {
                return ResourceManager.GetString("SaveEffluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveFirstPart {
            get {
                return ResourceManager.GetString("SaveFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Salinity.
        /// </summary>
        public static string ScenarioAmbientSalinity {
            get {
                return ResourceManager.GetString("ScenarioAmbientSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Temperature.
        /// </summary>
        public static string ScenarioAmbientTemperature {
            get {
                return ResourceManager.GetString("ScenarioAmbientTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Factor.
        /// </summary>
        public static string ScenarioDecayFactor {
            get {
                return ResourceManager.GetString("ScenarioDecayFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario is constant.
        /// </summary>
        public static string ScenarioIsConstant {
            get {
                return ResourceManager.GetString("ScenarioIsConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario length.
        /// </summary>
        public static string ScenarioLength {
            get {
                return ResourceManager.GetString("ScenarioLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manning Number.
        /// </summary>
        public static string ScenarioManningNumber {
            get {
                return ResourceManager.GetString("ScenarioManningNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario name.
        /// </summary>
        public static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Frequency.
        /// </summary>
        public static string ScenarioResultFrequency {
            get {
                return ResourceManager.GetString("ScenarioResultFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ScenarioStart {
            get {
                return ResourceManager.GetString("ScenarioStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        public static string ScenarioWindDirection {
            get {
                return ResourceManager.GetString("ScenarioWindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        public static string ScenarioWindSpeed {
            get {
                return ResourceManager.GetString("ScenarioWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a hydrometric site.
        /// </summary>
        public static string SelectAHydrometricSite {
            get {
                return ResourceManager.GetString("SelectAHydrometricSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file:.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server files.
        /// </summary>
        public static string ServerFiles {
            get {
                return ResourceManager.GetString("ServerFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup WebTide.
        /// </summary>
        public static string SetupWebTide {
            get {
                return ResourceManager.GetString("SetupWebTide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show and Hide .
        /// </summary>
        public static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide water levels.
        /// </summary>
        public static string ShowHideWaterLevels {
            get {
                return ResourceManager.GetString("ShowHideWaterLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show study area.
        /// </summary>
        public static string ShowStudyArea {
            get {
                return ResourceManager.GetString("ShowStudyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string South_abr {
            get {
                return ResourceManager.GetString("South_abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date and Time.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Flow.
        /// </summary>
        public static string StartFlow {
            get {
                return ResourceManager.GetString("StartFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pollution.
        /// </summary>
        public static string StartPollution {
            get {
                return ResourceManager.GetString("StartPollution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Salinity.
        /// </summary>
        public static string StartSalinity {
            get {
                return ResourceManager.GetString("StartSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Temperature.
        /// </summary>
        public static string StartTemperature {
            get {
                return ResourceManager.GetString("StartTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tides.
        /// </summary>
        public static string Tides {
            get {
                return ResourceManager.GetString("Tides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use decoupling files.
        /// </summary>
        public static string UseDecouplingFiles {
            get {
                return ResourceManager.GetString("UseDecouplingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use hydrometric.
        /// </summary>
        public static string UseHydrometric {
            get {
                return ResourceManager.GetString("UseHydrometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use salinity and temperature initial condition from result file.
        /// </summary>
        public static string UseSalinityAndTemperatureInitialConditionFromResultFile {
            get {
                return ResourceManager.GetString("UseSalinityAndTemperatureInitialConditionFromResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Node List.
        /// </summary>
        public static string ViewNodeList {
            get {
                return ResourceManager.GetString("ViewNodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Nodes.
        /// </summary>
        public static string ViewNodes {
            get {
                return ResourceManager.GetString("ViewNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Nodes on Map.
        /// </summary>
        public static string ViewNodesOnMap {
            get {
                return ResourceManager.GetString("ViewNodesOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web tide data at first node.
        /// </summary>
        public static string WebTideDataAtFirstNode {
            get {
                return ResourceManager.GetString("WebTideDataAtFirstNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTide Nodes.
        /// </summary>
        public static string WebTideNodes {
            get {
                return ResourceManager.GetString("WebTideNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind direction.
        /// </summary>
        public static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to go to a subsector below this sector and add hydrometric sites.
        /// </summary>
        public static string YouWillNeedToGoToASubsectorBelowThisSectorAndAddHydrometricSites {
            get {
                return ResourceManager.GetString("YouWillNeedToGoToASubsectorBelowThisSectorAndAddHydrometricSites", resourceCulture);
            }
        }
    }
}
