//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.ReportType.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportTypeViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportTypeViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.ReportType.Resources.ReportTypeViewRes", typeof(ReportTypeViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child section.
        /// </summary>
        public static string AddChildSection {
            get {
                return ResourceManager.GetString("AddChildSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new year.
        /// </summary>
        public static string AddNewYear {
            get {
                return ResourceManager.GetString("AddNewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sibling section.
        /// </summary>
        public static string AddSiblingSection {
            get {
                return ResourceManager.GetString("AddSiblingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add top section.
        /// </summary>
        public static string AddTopSection {
            get {
                return ResourceManager.GetString("AddTopSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box model.
        /// </summary>
        public static string BoxModel {
            get {
                return ResourceManager.GetString("BoxModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change to.
        /// </summary>
        public static string ClickHereToChangeTo {
            get {
                return ResourceManager.GetString("ClickHereToChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to parent.
        /// </summary>
        public static string ConvertToParent {
            get {
                return ResourceManager.GetString("ConvertToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to sub-section.
        /// </summary>
        public static string ConvertToSubSection {
            get {
                return ResourceManager.GetString("ConvertToSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy report section for item and year.
        /// </summary>
        public static string CopyReportSectionForItemAndYear {
            get {
                return ResourceManager.GetString("CopyReportSectionForItemAndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name will start with.
        /// </summary>
        public static string FileNameWillStartWith {
            get {
                return ResourceManager.GetString("FileNameWillStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Infrastructure {
            get {
                return ResourceManager.GetString("Infrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not static.
        /// </summary>
        public static string IsNotStatic {
            get {
                return ResourceManager.GetString("IsNotStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is static.
        /// </summary>
        public static string IsStatic {
            get {
                return ResourceManager.GetString("IsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike scenario.
        /// </summary>
        public static string MikeScenario {
            get {
                return ResourceManager.GetString("MikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike source.
        /// </summary>
        public static string MikeSource {
            get {
                return ResourceManager.GetString("MikeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New year.
        /// </summary>
        public static string NewYear {
            get {
                return ResourceManager.GetString("NewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report type created yet for {0}.
        /// </summary>
        public static string NoReportTypeCreatedYetFor_ {
            get {
                return ResourceManager.GetString("NoReportTypeCreatedYetFor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polllution source site.
        /// </summary>
        public static string PolSourceSite {
            get {
                return ResourceManager.GetString("PolSourceSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report section for year.
        /// </summary>
        public static string ReportSectionForYear {
            get {
                return ResourceManager.GetString("ReportSectionForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report section name.
        /// </summary>
        public static string ReportSectionName {
            get {
                return ResourceManager.GetString("ReportSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report sections.
        /// </summary>
        public static string ReportSections {
            get {
                return ResourceManager.GetString("ReportSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report section text.
        /// </summary>
        public static string ReportSectionText {
            get {
                return ResourceManager.GetString("ReportSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report types.
        /// </summary>
        public static string ReportTypes {
            get {
                return ResourceManager.GetString("ReportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide report section edit.
        /// </summary>
        public static string ShowOrHideReportSectionEdit {
            get {
                return ResourceManager.GetString("ShowOrHideReportSectionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide report section list.
        /// </summary>
        public static string ShowOrHideReportSectionList {
            get {
                return ResourceManager.GetString("ShowOrHideReportSectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide report type.
        /// </summary>
        public static string ShowOrHideReportType {
            get {
                return ResourceManager.GetString("ShowOrHideReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of file name.
        /// </summary>
        public static string StartOfFileName {
            get {
                return ResourceManager.GetString("StartOfFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsector.
        /// </summary>
        public static string Subsector {
            get {
                return ResourceManager.GetString("Subsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of item.
        /// </summary>
        public static string TVType {
            get {
                return ResourceManager.GetString("TVType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique code.
        /// </summary>
        public static string UniqueCode {
            get {
                return ResourceManager.GetString("UniqueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual plumes scenario.
        /// </summary>
        public static string VisualPlumesScenario {
            get {
                return ResourceManager.GetString("VisualPlumesScenario", resourceCulture);
            }
        }
    }
}
