//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebTools.Views.VisualPlumes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisualPlumeViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualPlumeViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebTools.Views.VisualPlumes.Resources.VisualPlumeViewRes", typeof(VisualPlumeViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acute MixZone.
        /// </summary>
        public static string AcuteMixZone {
            get {
                return ResourceManager.GetString("AcuteMixZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient.
        /// </summary>
        public static string Ambient {
            get {
                return ResourceManager.GetString("Ambient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Information.
        /// </summary>
        public static string AmbientInformation {
            get {
                return ResourceManager.GetString("AmbientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Salinity.
        /// </summary>
        public static string AmbientSalinity {
            get {
                return ResourceManager.GetString("AmbientSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Temperature.
        /// </summary>
        public static string AmbientTemperature {
            get {
                return ResourceManager.GetString("AmbientTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at depth.
        /// </summary>
        public static string AtDepth {
            get {
                return ResourceManager.GetString("AtDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Concentration.
        /// </summary>
        public static string BackgroundConcentration {
            get {
                return ResourceManager.GetString("BackgroundConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic MixZone.
        /// </summary>
        public static string ChronicMixZone {
            get {
                return ResourceManager.GetString("ChronicMixZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Direction.
        /// </summary>
        public static string CurrentDirection {
            get {
                return ResourceManager.GetString("CurrentDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Speed .
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay Rate.
        /// </summary>
        public static string DecayRate {
            get {
                return ResourceManager.GetString("DecayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string DepthCap {
            get {
                return ResourceManager.GetString("DepthCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuser Information.
        /// </summary>
        public static string DiffuserInformation {
            get {
                return ResourceManager.GetString("DiffuserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent Concentration.
        /// </summary>
        public static string EffluentConcentration {
            get {
                return ResourceManager.GetString("EffluentConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent Flow.
        /// </summary>
        public static string EffluentFlow {
            get {
                return ResourceManager.GetString("EffluentFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent Salinity.
        /// </summary>
        public static string EffluentSalinity {
            get {
                return ResourceManager.GetString("EffluentSalinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffluentTemperature.
        /// </summary>
        public static string EffluentTemperature {
            get {
                return ResourceManager.GetString("EffluentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Field Current Direction.
        /// </summary>
        public static string FarFieldCurrentDirection {
            get {
                return ResourceManager.GetString("FarFieldCurrentDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Field Current Speed.
        /// </summary>
        public static string FarFieldCurrentSpeed {
            get {
                return ResourceManager.GetString("FarFieldCurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Field Diffusion Coefficient.
        /// </summary>
        public static string FarFieldDiffusionCoefficient {
            get {
                return ResourceManager.GetString("FarFieldDiffusionCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Ambient.
        /// </summary>
        public static string HideAmbient {
            get {
                return ResourceManager.GetString("HideAmbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Angle.
        /// </summary>
        public static string HorizontalAngle {
            get {
                return ResourceManager.GetString("HorizontalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item.
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results yet.
        /// </summary>
        public static string NoResultsYet {
            get {
                return ResourceManager.GetString("NoResultsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not used.
        /// </summary>
        public static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Ports.
        /// </summary>
        public static string NumberOfPorts {
            get {
                return ResourceManager.GetString("NumberOfPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollutant Decay Rate.
        /// </summary>
        public static string PollutantDecayRate {
            get {
                return ResourceManager.GetString("PollutantDecayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Depth.
        /// </summary>
        public static string PortDepth {
            get {
                return ResourceManager.GetString("PortDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Diameter.
        /// </summary>
        public static string PortDiameter {
            get {
                return ResourceManager.GetString("PortDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Elevation.
        /// </summary>
        public static string PortElevation {
            get {
                return ResourceManager.GetString("PortElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Spacing.
        /// </summary>
        public static string PortSpacing {
            get {
                return ResourceManager.GetString("PortSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Results.
        /// </summary>
        public static string RawResults {
            get {
                return ResourceManager.GetString("RawResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Visual Plume List Scenario.
        /// </summary>
        public static string ReturnToVPList {
            get {
                return ResourceManager.GetString("ReturnToVPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a new scenario with Visual Plume and come back to this page to view the results..
        /// </summary>
        public static string ReturnVPScenarioList {
            get {
                return ResourceManager.GetString("ReturnVPScenarioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Name.
        /// </summary>
        public static string ScenarioName {
            get {
                return ResourceManager.GetString("ScenarioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ambient.
        /// </summary>
        public static string ShowAmbient {
            get {
                return ResourceManager.GetString("ShowAmbient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic ... in a near future..
        /// </summary>
        public static string ShowGraphicFuture {
            get {
                return ResourceManager.GetString("ShowGraphicFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use as best.
        /// </summary>
        public static string UseAsBest {
            get {
                return ResourceManager.GetString("UseAsBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Angle.
        /// </summary>
        public static string VerticalAngle {
            get {
                return ResourceManager.GetString("VerticalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working ....
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
